Glusk/sprouts

- .gitignore
> Issue #7 Added local.properties to .gitignore.

- .gitignore
- local.properties
> #7 Added local.properties to .gitignore.

- travis.yml
> Issue #11 Added travis.yml

- README.md
> #17 Added README with build instructions

- core/build.gradle
- core/config/checkstyle/checkstyle.xml
- core/src/main/java/com/github/glusk2/sprouts/Sprouts.java
- core/src/main/java/com/github/glusk2/sprouts/geom/BSplineControlPoints.java
- core/src/main/java/com/github/glusk2/sprouts/geom/BezierCurve.java
- core/src/main/java/com/github/glusk2/sprouts/geom/CachedCurve.java
- core/src/main/java/com/github/glusk2/sprouts/geom/Curve.java
- core/src/main/java/com/github/glusk2/sprouts/geom/PerpDistSimpl.java
- core/src/main/java/com/github/glusk2/sprouts/geom/Polyline.java
- core/src/main/java/com/github/glusk2/sprouts/geom/package-info.java
- core/src/main/java/com/github/glusk2/sprouts/package-info.java
- core/src/test/java/com/github/glusk2/sprouts/geom/BSplineControlPointsTest.java
- core/src/test/java/com/github/glusk2/sprouts/geom/package-info.java
> #22 Refactored the project to satisfy checkstyle checks.

- core/src/main/java/com/github/glusk2/sprouts/geom/PerpDistSimpl.java
> #24 Replaced custom perpendicular distance with libGDX's version.

- core/src/main/java/com/github/glusk2/sprouts/geom/BSplineControlPoints.java
- core/src/test/java/com/github/glusk2/sprouts/geom/BSplineControlPointsTest.java
> #26 Fixed B-Splines control points for sample size = 3.

- core/src/test/java/com/github/glusk2/sprouts/geom/BSplineControlPointsTest.java
> #28 Added epsilonEquals.

- core/src/main/java/com/github/glusk2/sprouts/comb/CircularIterator.java
- core/src/main/java/com/github/glusk2/sprouts/comb/ClockwiseComparator.java
- core/src/main/java/com/github/glusk2/sprouts/comb/Edge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/Face.java
- core/src/main/java/com/github/glusk2/sprouts/comb/FromAdjacencyMap.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PlanarFace.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PlanarGraph.java
- core/src/main/java/com/github/glusk2/sprouts/comb/Vertex.java
- core/src/main/java/com/github/glusk2/sprouts/comb/package-info.java
- core/src/test/java/com/github/glusk2/sprouts/comb/ClockwiseComparatorTest.java
- core/src/test/java/com/github/glusk2/sprouts/comb/FromAdjacencyMapTest.java
- core/src/test/java/com/github/glusk2/sprouts/comb/package-info.java
> #30 #31 Added combinatorial representation stub.

- .gitignore
- core/src/main/java/com/github/glusk2/sprouts/comb/ClockwiseComparator.java
- core/src/test/java/com/github/glusk2/sprouts/comb/ClockwiseComparatorTest.java
> #32 #34 Typo fix, added vscode to gitignore

- core/src/main/java/com/github/glusk2/sprouts/comb/FromAdjacencyMap.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PlanarGraph.java
- core/src/test/java/com/github/glusk2/sprouts/comb/FromAdjacencyMapTest.java
> #36 Added face detection.

- core/src/main/java/com/github/glusk2/sprouts/geom/CurveApproximation.java
> #39 Added curve approximation.

- core/src/main/java/com/github/glusk2/sprouts/Sprouts.java
> #38 Added round joins polyline drawing.

- README.md
- appveyor.yml
> #47 Added Appveyor CI setup.

- html/build.gradle
> #52 Fixed the Gradle javadoc task

- core/src/main/java/com/github/glusk2/sprouts/Sprouts.java
- core/src/main/java/com/github/glusk2/sprouts/comb/InitialCobweb.java
- core/src/main/java/com/github/glusk2/sprouts/comb/StraightLineEdge.java
> #44 Added InitialCobweb

- core/src/main/java/com/github/glusk2/sprouts/comb/CompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/ReversedCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/StraightLineEdge.java
- core/src/test/java/com/github/glusk2/sprouts/comb/ReversedCompoundEdgeTest.java
> Add compound edge

- core/src/main/java/com/github/glusk2/sprouts/comb/NextCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/ReversedCompoundEdge.java
- core/src/test/java/com/github/glusk2/sprouts/comb/NextCompoundEdgeTest.java
> Next compound edge

- core/src/main/java/com/github/glusk2/sprouts/comb/CachedCompoundEdge.java
> #60 Added CachedCompundEdge

- core/src/main/java/com/github/glusk2/sprouts/PresetSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/RenderedSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/Sprouts.java
- core/src/main/java/com/github/glusk2/sprouts/Submove.java
- core/src/main/java/com/github/glusk2/sprouts/comb/CachedCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/CompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/ExtendedEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/Graph.java
- core/src/main/java/com/github/glusk2/sprouts/comb/InitialCobweb.java
- core/src/main/java/com/github/glusk2/sprouts/comb/LocalRotations.java
- core/src/main/java/com/github/glusk2/sprouts/comb/NextCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PresetGraph.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PresetRotations.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PresetVertex.java
- core/src/main/java/com/github/glusk2/sprouts/comb/ReversedCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/comb/StraightLineEdge.java
- core/src/main/java/com/github/glusk2/sprouts/geom/PolylinePiece.java
- core/src/main/java/com/github/glusk2/sprouts/geom/TrimmedPolyline.java
- core/src/test/java/com/github/glusk2/sprouts/comb/NextCompoundEdgeTest.java
- core/src/test/java/com/github/glusk2/sprouts/comb/PresetGraphTest.java
- core/src/test/java/com/github/glusk2/sprouts/comb/PresetRotationsTest.java
- core/src/test/java/com/github/glusk2/sprouts/comb/ReversedCompoundEdgeTest.java
> Add move impl

- core/src/main/java/com/github/glusk2/sprouts/PresetSubmove.java
> #72 Minor direction correction

- core/src/main/java/com/github/glusk2/sprouts/comb/PresetRotations.java
> #73 Fixed a javadoc error

- core/src/main/java/com/github/glusk2/sprouts/comb/PresetRotations.java
- core/src/test/java/com/github/glusk2/sprouts/comb/PresetRotationsTest.java
> #81 Fixed a bug; added a test.

- core/src/main/java/com/github/glusk2/sprouts/PresetSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/Sprouts.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PresetRotations.java
- core/src/main/java/com/github/glusk2/sprouts/geom/IsPointOnLineSegment.java
- core/src/main/java/com/github/glusk2/sprouts/geom/PerpDistSimpl.java
- core/src/main/java/com/github/glusk2/sprouts/geom/PolylinePiece.java
- core/src/test/java/com/github/glusk2/sprouts/comb/PresetRotationsTest.java
- core/src/test/java/com/github/glusk2/sprouts/geom/IsPointOnLineSegmentTest.java
> Fix cobweb tear

- core/src/main/java/com/github/glusk2/sprouts/SubmoveElement.java
- core/src/main/java/com/github/glusk2/sprouts/comb/FaceIntersectionSearch.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PolylineIntersectionSearch.java
> Submove validation

- core/src/main/java/com/github/glusk2/sprouts/comb/Graph.java
- core/src/main/java/com/github/glusk2/sprouts/comb/InitialCobweb.java
- core/src/main/java/com/github/glusk2/sprouts/comb/PresetGraph.java
- core/src/main/java/com/github/glusk2/sprouts/comb/TransformedGraph.java
- core/src/main/java/com/github/glusk2/sprouts/geom/PolylinePiece.java
- core/src/main/java/com/github/glusk2/sprouts/ui/MoveDrawing.java
- core/src/main/java/com/github/glusk2/sprouts/ui/SproutAdd.java
> #107 Added a SproudAdd Snapshot

- core/src/main/java/com/github/glusk2/sprouts/MainScreen.java
- core/src/main/java/com/github/glusk2/sprouts/SubmoveElement.java
- core/src/main/java/com/github/glusk2/sprouts/ui/BeforeMove.java
- core/src/main/java/com/github/glusk2/sprouts/ui/MoveDrawing.java
- core/src/main/java/com/github/glusk2/sprouts/ui/SproutAdd.java
> #101 Added game board bounds to Submove validation

- README.md
> #86 Added LoC badge

- core/src/main/java/com/github/glusk2/sprouts/SubmoveElement.java
> #92 Fixed Submove validation

- android/build.gradle
- android/src/com/github/glusk2/sprouts/AndroidLauncher.java
- android/src/com/github/glusk2/sprouts/package-info.java
- build.gradle
- core/build.gradle
- desktop/src/com/github/glusk2/sprouts/desktop/DesktopLauncher.java
- desktop/src/com/github/glusk2/sprouts/desktop/package-info.java
- html/src/com/github/glusk2/sprouts/client/HtmlLauncher.java
- html/src/com/github/glusk2/sprouts/client/package-info.java
- ios/src/com/github/glusk2/sprouts/IOSLauncher.java
- ios/src/com/github/glusk2/sprouts/package-info.java
> #22 Added checkstyle to the whole project

- .travis.yml
- android/build.gradle
> #116 Centralized project version

- .travis.yml
- build.gradle
- deploy.sh
> Deploy itchio

- .travis.yml
> #122 Fixed deploy condition

- .travis.yml
> #124 Fixed deploy typo

- .travis.yml
- deploy.sh
> #126 Fixed release .apk location

- .travis.yml
> #128 Skipped cleanup

- android/src/com/github/glusk2/sprouts/android/AndroidLauncher.java
- core/src/main/java/com/github/glusk2/sprouts/core/Sprouts.java
- desktop/src/com/github/glusk2/sprouts/desktop/DesktopLauncher.java
- html/src/com/github/glusk2/sprouts/html/HtmlLauncher.java
- ios/src/com/github/glusk2/sprouts/ios/IOSLauncher.java
> #131 Fixed small resolution problems

- .travis.yml
> #117 Added Travis setup for javadoc publish

- core/src/main/java/com/github/glusk2/sprouts/core/comb/PresetGraph.java
> #140 Greyed-out dead sprouts

- deploy.sh
> #143 Fixed butler versioning

- android/build.gradle
- build.gradle
> #144 Bumped version to v0.8.0

- deploy.sh
> #143 Properly applied buttler versioning

- core/src/main/java/com/github/glusk2/sprouts/core/comb/IsMovePossible.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/IsMovePossibleInFace.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/BeforeMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/util/Check.java
- core/src/main/java/com/github/glusk2/sprouts/core/util/package-info.java
> Add endgame

- core/src/main/java/com/github/glusk2/sprouts/core/SubmoveElement.java
> #151 Bug fix

- .travis.yml
- README.md
- build.gradle
> #154 Added coveralls

- .travis.yml
> #154 Added coverage to codacy

- core/src/main/java/com/github/glusk2/sprouts/core/comb/CachedCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/NextCompoundEdge.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/ReversedCompoundEdge.java
> #157 Removed CompoundEdge duplication

- core/src/main/java/com/github/glusk2/sprouts/core/SubmoveElement.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/FaceIntersectionSearch.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/GraphCreation.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/NearestSproutSearch.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/PolylineEdge.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/PolylineIntersectionSearch.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/PresetVertex.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/VoidVertex.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/SproutAdd.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/ClockwiseComparatorTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/FaceIntersectionSearchTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/NextCompoundEdgeTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/PresetGraphTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/PresetRotationsTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/ReversedCompoundEdgeTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/SubmoveTransformationTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/geom/BSplineControlPointsTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/geom/IsPointOnLineSegmentTest.java
> Add labels

- .rultor.yml
- README.md
- build.gradle
> #161 Added automated versioning and release

- build.gradle
- gradle.properties
> #161 Moved version to gradle.properties

- gradle.properties
> #161 Dummy version bump to commit gradle.properties

- android/build.gradle
- build.gradle
> #173 Revised android sdk paths

- .rultor.yml
- build.gradle
- gradle.properties
> Reconfigure release

- .rultor.yml
> #178 resolve rultor release config

- .travis.yml
> #180 Updated travis tag condition

- core/src/main/java/com/github/glusk2/sprouts/core/SubmoveElement.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/IsMovePossible.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/IsSubmovePossibleInFace.java
> #189 Corrected Submove gray-out

- .github/workflows/build.yml
- README.md
> #194 Update badges

- .github/workflows/pull-request.yml
> #198 Fixed

- .github/workflows/release.yml
- .github/workflows/tagged-release.yml
- deploy.sh
> GitHub release

- .github/workflows/release.yml
- .github/workflows/tagged-release.yml
> Fix release

- core/src/main/java/com/github/glusk2/sprouts/core/comb/Graph.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/PresetGraph.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/TransformedGraph.java
> #203 Removed Graph#with(Vertex)

- core/src/main/java/com/github/glusk2/sprouts/core/MainScreen.java
> #182 Added instructions button

- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsTooltip.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/MoveDrawing.java
- core/src/test/java/com/github/glusk2/sprouts/core/comb/SproutsTooltipTest.java
> #209 Added tooltip

- core/src/main/java/com/github/glusk2/sprouts/core/CobwebSwitch.java
- core/src/main/java/com/github/glusk2/sprouts/core/MainScreen.java
- core/src/main/java/com/github/glusk2/sprouts/core/RenderedMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/RenderedSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsGameState.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsTooltip.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/BeforeMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/MoveDrawing.java
- core/src/main/java/com/github/glusk2/sprouts/core/ui/SproutAdd.java
- core/src/test/java/com/github/glusk2/sprouts/core/ui/SproutAddTest.java
> Cobweb toggle

- core/src/main/java/com/github/glusk2/sprouts/core/GameBoard.java
- core/src/main/java/com/github/glusk2/sprouts/core/MainScreen.java
- core/src/main/java/com/github/glusk2/sprouts/core/ResetDialog.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsFaces.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsStateAfterMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/comb/SproutsStateAfterSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/Move.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/RenderedMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/RenderedSubmove.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/Submove.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/SubmoveElement.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/SubmoveHead.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/SubmoveSequence.java
- core/src/main/java/com/github/glusk2/sprouts/core/moves/package-info.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/BeforeMove.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/GameBoard.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/MoveDrawing.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/ResetDialog.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/Snapshooter.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/Snapshot.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/SproutAdd.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/TouchEventSnapshooter.java
- core/src/main/java/com/github/glusk2/sprouts/core/snapshots/package-info.java
- core/src/test/java/com/github/glusk2/sprouts/core/snapshots/SproutAddTest.java
- core/src/test/java/com/github/glusk2/sprouts/core/snapshots/package-info.java
- core/src/test/java/com/github/glusk2/sprouts/core/ui/package-info.java
> Package reorg

- core/src/main/java/com/github/glusk2/sprouts/core/MainScreen.java
> #182 Improved instructions
